version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: salesbot
      POSTGRES_USER: salesbot
      POSTGRES_PASSWORD: salesbot123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U salesbot"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_DSN=postgresql+asyncpg://salesbot:salesbot123@postgres/salesbot
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CALENDLY_URL=${CALENDLY_URL:-https://calendly.com/justin-erezcapital/30min}
      - DEBUG_LOCAL=true
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
    command: python -m uvicorn api.main:app --reload --host 0.0.0.0 --port 8000

volumes:
  redis_data:
  postgres_data: