apiVersion: v1
kind: Service
metadata:
  name: sales-discovery-bot
  namespace: agents
  labels:
    app: sales-discovery-bot
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: sales-discovery-bot
    component: api
---
# Optional: Expose via Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sales-discovery-bot
  namespace: agents
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # CORS for widget embedding
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  tls:
  - hosts:
    - salesbot.insta-agents.com
    secretName: salesbot-tls
  rules:
  - host: salesbot.insta-agents.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sales-discovery-bot
            port:
              number: 80