name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'build-*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      run: |
        IMAGE_TAG="ghcr.io/${{ github.repository }}:${{ github.sha }}"
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
    
    - name: Save image reference
      run: |
        echo "${{ env.IMAGE_TAG }}" > image-tag.txt
        
    - name: Upload image tag artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-tag
        path: image-tag.txt
