name: Direct Docker Push

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/docker-direct.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      run: |
        echo "dckr_pat_hCWY83pT8BWzna3Ztpd0YLx0Fec" | docker login -u justininstabids --password-stdin
    
    - name: Build and push
      run: |
        docker build -t justininstabids/sales-discovery-bot:latest .
        docker push justininstabids/sales-discovery-bot:latest
        echo "Image pushed to: justininstabids/sales-discovery-bot:latest"
