name: Test Docker Login

on:
  workflow_dispatch:

jobs:
  test-login:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Docker Hub Login
      run: |
        echo "dckr_pat_hCWY83pT8BWzna3Ztpd0YLx0Fec" | docker login -u justininstabids --password-stdin
        echo "Login successful!"
        docker logout
